
#TARGET=amigaos3


PREF=/opt/netsurf/m68k-unknown-amigaos
GCCSDK_INSTALL_ENV = $(PREF)/env
GCCSDK_INSTALL_CROSSBIN = $(PREF)/cross/bin
CFLAGS += -D__clib2__ -I$(PREF)/m68k-unknown-amigaos/include -I$(PREF)/env/include \
        -I$(PREF)/env/m68k-unknown-amigaos/sys-include -I$(PREF)/env/netinclude 
LDFLAGS += -L/mnt/d/opt/netsurfy/netsurf-all-3.11/inst-amigaos3-art/lib -lnet -lamisslauto
PKG_CONFIG_PATH=/mnt/d/opt/netsurfy/netsurf-all-3.11/inst-amigaos3-art/lib/pkgconfig:/opt/netsurf/m68k-unknown-amigaos/env/lib/pkgconfig	

CC := $(PREF)/cross/bin/m68k-unknown-amigaos-gcc
AS := $(PREF)/cross/bin/m68k-unknown-amigaos-as
LD := $(PREF)/cross/bin/m68k-unknown-amigaos-ld
AR=ar

HOST_GCC=gcc

### To enable/disable PNG support, uncomment the appropriate line below.
# override NETSURF_USE_PNG := YES
# override NETSURF_USE_PNG := NO

### To enable/disable SVGTiny support, uncomment the appropriate line below.
# override NETSURF_USE_NSSVG := YES
# override NETSURF_USE_NSSVG := NO

### To enable/disable RSVG support, uncomment the appropriate line below.
# override NETSURF_USE_RSVG := YES
# override NETSURF_USE_RSVG := NO

### To enable/disable BMP support, uncomment the appropriate line below.
# override NETSURF_USE_BMP := YES
# override NETSURF_USE_BMP := NO

### To make the framebuffer front end use freetype for text, uncomment the
### following line
# override NETSURF_FB_FONTLIB := freetype

### To disable JavaScript support, uncomment the appropriate line below.
# override NETSURF_USE_DUKTAPE := NO

### To change flags to javascript binding generator
# GBFLAGS:=-g

### To enable ASAN and UBSAN support in builds regardless of target
# override NETSURF_USE_SANITIZER := YES

### If you're using the sanitizers and you want it to stop on failure...
# override NETSURF_RECOVER_SANITIZERS := NO

### To change the compiled in log level, alter this.
# Valid options are: DEEPDEBUG, DEBUG, VERBOSE, INFO, WARNING, ERROR, CRITICAL
 override NETSURF_LOG_LEVEL := DEEPDEBUG

### To change the compiled in default log, change this
# override NETSURF_BUILTIN_LOG_FILTER := "(level:WARNING || cat:jserrors)"

### To change the compiled in *verbose* log, change this
# override NETSURF_BUILTIN_VERBOSE_FILTER := "(level:VERBOSE || cat:jserrors)"

